Validation = {
    "layer": ["NORMAL", "ABOVE ", "BELOW "],
    "maximize": ["VERTICAL", "HORIZONTAL", "yes", "no"],
    "context": [
        "Frame",
        "Client",
        "Desktop",
        "Root",
        "Titlebar",
        # "Top, Bottom, Left, Right",
        # "TLCorner, TRCorner, BLCorner, BRCorner",
        "Icon",
        "Iconify",
        "Maximize",
        "Close",
        "AllDesktops",
        "Shade",
        "MoveResize",
    ],
    "event": [
        "Press",
        "Click",
        "DoubleClick",
        "Release",
        "Drag",
    ],
    "actions": [
        "Execute",
        "ShowMenu",
        "NextWindow",
        "PreviousWindow",
        "DirectionalCycleWindows",
        "DirectionalTargetWindow",
        "GoToDesktop",
        "AddDesktop",
        "RemoveDesktop",
        "ToggleShowDesktop",
        "ToggleDockAutohide",
        "Reconfigure",
        "Restart",
        "Exit",
        "SessionLogout",
        "Debug",
        "Focus",
        "Raise",
        "Lower",
        "RaiseLower",
        "Unfocus",
        "FocusToBottom",
        "Iconify",
        "Close",
        "ToggleShade",
        "Shade",
        "Unshade",
        "ToggleOmnipresent",
        "ToggleMaximize",
        "Maximize",
        "Unmaximize",
        "ToggleFullscreen",
        "ToggleDecorations",
        "Decorate",
        "Undecorate",
        "SendToDesktop",
        "Move",
        "Resize",
        "MoveResizeTo",
        "MoveRelative",
        "ResizeRelative",
        "MoveToEdge",
        "GrowToEdge",
        "GrowToFill",
        "ShrinkToEdge",
        "If",
        "ForEach",
        "Stop",
        "ToggleAlwaysOnTop",
        "ToggleAlwaysOnBottom",
        "SendToLayer",
    ],
}
